module.exports = {
  config: {
    name: "8ball",
    aliases: ["ball", "8b", "boule"],
    version: "3.0",
    author: "SamyCharlesღ",
    countDown: 3,
    role: 0,
    description: {
      fr: "Pose une question et reçois une réponse aléatoire parmi 100 🔮"
    },
    category: "fun"
  },

  onStart: async function ({ message, args, event }) {
    const question = args.join(" ");
    if (!question) {
      return message.reply("❓ Pose ta question après la commande.\nExemple : 8ball Est-ce que je vais devenir célèbre ?");
    }

    const responses = [
      "✅ Oui",
      "❌ Non",
      "🤔 Peut-être",
      "⏳ Demande plus tard",
      "🔥 Bien sûr que oui",
      "💩 Jamais de la vie",
      "💘 Tu vas tomber amoureux",
      "🔮 Le destin est en ta faveur",
      "😈 Prépare-toi au pire",
      "🌈 La chance te sourit",
      "💤 Trop fatigué pour répondre",
      "😹 T’es sérieux là ?",
      "🍀 Oui, avec un peu de chance",
      "👻 Réponse introuvable, esprit absent",
      "🎲 Lancer de dé : 1 = non",
      "📉 Mauvais signe...",
      "📈 C’est ton moment",
      "📱 Tu reçois un message bientôt",
      "🚫 Tu ne veux pas savoir",
      "😇 Le karma est avec toi",
      "👀 Quelqu’un t’observe",
      "🫣 Tu vas regretter la réponse",
      "🤷 Réponse pas claire",
      "👑 Bien sûr, t’es un roi/reine",
      "🧠 Utilise ta tête, pas ta boule",
      "🎭 Tu joues un rôle…",
      "💀 Mauvais karma",
      "❤️‍🔥 Oui, mais attention au cœur",
      "🤑 L’argent va venir",
      "🥶 Tu vas te faire ghost",
      "👨‍🚀 C’est loin d’être sûr",
      "🧸 Quelqu’un t’aime secrètement",
      "🍔 Mange d’abord, réfléchis après",
      "📅 Demain peut-être",
      "🛑 STOP. Ne fais pas ça.",
      "📢 Annonce surprise à venir",
      "💼 Focus sur tes objectifs",
      "😵‍💫 Réponse perdue en multivers",
      "🐢 Trop lent pour te répondre",
      "🪞 Regarde-toi et tu sauras",
      "🎇 C’est ton année",
      "🧿 Protège-toi du mauvais œil",
      "🥺 Oui mais doucement",
      "🚀 Tu vas décoller",
      "👣 Une nouvelle personne arrive",
      "💥 Explosion d’émotion à venir",
      "🎃 Frissons garantis",
      "🫀 Ton cœur va s’emballer",
      "🥷 Fais-le en cachette",
      "📸 Moment à immortaliser",
      "🫡 Fonce !",
      "🪙 Pile ou face : pile = oui",
      "🧩 Trop de pièces manquantes",
      "🧃 Bois de l’eau et repense-y",
      "🥀 Relation toxique détectée",
      "💡 Bonne idée",
      "💡 Mauvaise idée",
      "🤖 Demande à ChatGPT (moi 😏)",
      "🧼 Nettoie ton énergie d’abord",
      "🛐 Prie un peu avant",
      "🌌 L’univers dit oui",
      "🌪️ Tu risques de tout perdre",
      "📀 Mise à jour en cours...",
      "📚 La réponse est dans un livre",
      "🕳️ Plongée dans l’inconnu",
      "🛸 Tu vas être enlevé par des aliens",
      "🎤 T’as la parole bientôt",
      "🎧 Écoute ton instinct",
      "🛏️ Dors dessus avant de décider",
      "🌊 Va avec le courant",
      "🏝️ Isolement à prévoir",
      "📦 Une surprise arrive",
      "💔 Cœur brisé détecté",
      "💓 C’est réciproque 💕",
      "🕰️ Tout vient à point",
      "🔗 Un lien va se briser",
      "🌍 Changement majeur en vue",
      "🎁 Un cadeau arrive",
      "🐾 Suis les signes",
      "🛤️ Tu es sur le bon chemin",
      "💣 BOOM. C’est oui",
      "🛡️ Protège-toi des faux amis",
      "😴 Tu rêves éveillé",
      "🧊 C’est froid comme réponse",
      "🔥 C’est chaud, vas-y !",
      "🌘 Patience, jeune padawan",
      "🥵 Trop risqué",
      "🥳 Victoire assurée",
      "📲 Tu vas recevoir une bonne nouvelle",
      "🔔 Quelqu’un pense à toi",
      "🫥 On ne veut pas te blesser… mais non",
      "🙃 Tu le sais déjà",
      "🤡 Arrête de te mentir",
      "🫠 Fuis cette situation",
      "👽 Réponse venue d’ailleurs : OUI",
      "🐉 Tu débloques un niveau secret",
      "🥹 Oui mais tu vas pleurer",
      "🕹️ C’est un jeu, amuse-toi",
      "🚧 En construction, repasse plus tard",
      "🗿 Demande à la pierre (elle dit non)",
      "🎨 Crée ta propre réponse",
      "📬 Tu reçois la réponse bientôt",
      "🤬 Tu veux que je dise quoi là ?",
      "📞 Quelqu’un va t’appeler",
      "🎢 Montagnes russes à venir",
      "🥰 Quelqu’un craque pour toi",
      "💬 Message inattendu à venir",
      "😈 Ose, t’as rien à perdre"
    ];

    const random = responses[Math.floor(Math.random() * responses.length)];

    return message.reply(`🎱 *Question* : ${question}\n✨ *Réponse magique* : ${random}`);
  }
};
